### PR TITLE
Improve Constants Management in Codebase #16

### LINKED ISSUE #4: Improve the Prompts sent to OpenAI API
The [current prompts](https://github.com/davidalami/VulnMapAI/blob/main/advising/prompts.yaml) can be made more concise, clear, and informative to possibly receive better and more accurate responses from the OpenAI. The task is to review and improve the wording and structure of the existing prompts.
While the current prompts provide some clarity on the desired outcome, refining their structure and wording can help achieve better and more accurate responses from the OpenAI API.

### LINKED ISSUE #16: Improve Constants Management in Codebase
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when constants are scattered across multiple modules and files, leading to potential redundancy and lack of clarity.

**Describe the solution you'd like**
Creating container classes in a dedicated file, where all constants related to the functionality will be housed. 

**Describe alternatives you've considered**
Storing constants in a standalone constants.py file without a container class, but this could lead to potential naming clashes and lacks contextual grouping.

### PR DESCRIPTION
**Pull request by badoolee**
### Pull Request Description

Please include a brief description of the changes this PR introduces and the issue it closes or the feature it adds.

### Type of Change

- [x] Bug fix (non-breaking change which fixes an issue)

### How Has This Been Tested?
- [x] New and existing unit tests pass locally with my changes

### Additional Context (if any)

Provide any additional context or screenshots about the feature request or bug report here.
I created some global variables which helps to improve the hard code wordings and it will make it easier to make corrections later in the future. Rather than going over the codes to make corrections

### CODE REVIEW

**Comment by davidalami** [comment]
Hey @badoolee , thank you for your contribution! 
To enhance the organization and maintainability of the code, I'd recommend moving the constants into a separate file `constants.py`  which should be on the same level as `config.py`. 
Then, it would be great to create container classes keeping only constants, for example

```
class AdvisorConstants:
    API_KEY_ERROR = "OPENAI_API_KEY NOT SET AS AN ENVIRONMENT VARIABLE"
    ....
```
Also, there are other constants in the code like these ones, therefore it is possible to create `PenetrationTesterConstants` class and others.
Would you like to tackle this challenge?

**Comment by badoolee** [comment]
Yeah, I can do that.

**Review by badoolee — COMMENTED** [review]
Created a constant.py where all constants in the code are placed in container classes only for constants.

**Review by davidalami — CHANGES_REQUESTED** [review]
Great job on that one! 
We are almost there. With the latest changes the build fails, because there is no `constants.py` file in the docker image. We need to copy this file to the image during build.
@badoolee , we need to edit build/final_image/Dockerfile, copying the constants file as follows:
```
COPY constants.py .
```

**Review by badoolee — COMMENTED** [review]
i copied the constants file in the Dockerfile just as you instructed sir.

**Review by davidalami — APPROVED** [review]
@badoolee , kudos on stepping up and taking initiative to improve the codebase! Your efforts to centralize and manage constants better will certainly go a long way in enhancing the readability and maintainability of the project.
Your dedication and hard work are truly appreciated!

**Comment by badoolee** [comment]
Thank you for accepting my pull request sir. i hope to work more with you later in future.

**Comment by badoolee** [comment]
Hello sir, i forgot to inform that i'm a participate of Hacktoberfest and a
hactoberfest tag must be in any pull request i make before it can be
accepted. i hope it's not too late to help me add the tag sir?

**Comment by davidalami** [comment]
Hello @badoolee , done!

**Pull request merged**
